name: Update Packagist

on:
  push:
    branches: [main]
    tags: ['v*']

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist
        run: |
          curl -fsSL -XPOST \
            -H 'content-type:application/json' \
            "https://packagist.org/api/update-package?username=${PACKAGIST_USERNAME}&apiToken=${PACKAGIST_TOKEN}" \
            -d '{"repository":{"url":"https://github.com/teh-hippo/roundcube-remember-me"}}'
        env:
          PACKAGIST_USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}
